language: java
sudo: false
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
after_success:
- chmod -R 777 ./travis/after_success.sh
- "./travis/after_success.sh"
env:
  global:
  - secure: 0T3uh5LpDsHEBrArxfMJ6rvqF8wtqMYssyAblBJ2DXRz2rNslaeQ33KPEwPHtvThkg01tB7K1+J/5iMwtfHeAnfa+p2rt4LJjBCSLufQ/MObeKQz+OWHthfteKLRpv2MHh06hZSh75hIYCbflsm6PqjjGVuvbk+uX4Xw+vFIuCQYDTWbyEhpE0thyC97WQZhF5dAp04VBRXTF/3Qo6AeuhpeczKyoH0O8Ql6YAQbpR/npmWClRlVOwtH5XMAS5c06LNAbOWeeMK0+BUFQ/6yG7vOlgCDy+2Xc528njsy0xdUcnK6n2uSr63hPH2NCqUpMjQxiiC/b2IhxPKiGlGC/M3CgAcD44NLVPc20EtW1ZD1GILLuT3hw40K+EYzFmTkZWig8aKulPLVY8WPt6AFUYKC2QjkuDEK1HlXfNHJ2MzL0E6uDyoSUb8tWjkJurZIXcsEbSA1YpGFlQekFlLWTPeBV9/sWjojf38IuK2oTYYQRJcQ2HJQ+MHCWidf+pS1ZLQJI5klSQhetkLWvC+ps2kg1wHgxWTcEp6BX2qyUJTgI2h1uvlzm/LCoqYsGpHkSWegKCyPo2gnUOm9uiwseWQ969rBJmqieIqHwrtz82Vbz0GwoUP3rBUPMOvfLxqVKCGQKHrxXyhZbne2X3qxdSdO7TzclHRx4I+P71JTEjU=
  - secure: H4jcONLaXbllE8sey3vaNQbbKyGmNFGBNQFnbnctBjuCXN0YjuDS3ddJkFhryRUBswL1v5XK1oAh1I+MDT1n8KbwJNHYEcCcwvEWDeTkFtDRzzeS0XZ+qT6qIeV8E6tezdtdyAPp47miKuF33woUoB48+jknZxr8+GZS9OYvwOgvdjxs4JjJUvemJEYQvfwOA6m0udq+LnVN7SEj6lLc6Rpl7riT5hZH45NJXOfKX6lcXOuEbVO9iFPnbabFtM1GAK0512BXtZmqHizXCSSv9af4spR3tZdCyEic0fCSdkhC5cDEMC/ZykHrwjSSxqQxMaDiRa/RBRclI5oQ08sPMyMv9RN0DsGYTPVwgaeLR5IS7dmzL+21GSanLa8LgTaRkcfzn9Fm7yrUb3MxG1d/ZWej42HnNOMV7h6ApIFoNEOKed+XqpGGcslri0gZjFL3mwEFveXWa837R5BRdNC4XKUpiTEyz5luMQJhc/Ob0bBRCkrfe5SsRtoIKsJ6c2W29Wj7x60Xu6QS5M4G732OfzzwlFbLOqPQJtH+dvMCTnYTb8COMvaCl2qCd7YbIHJsEB6aEekO/Et6tQtWo0Gh7kP+Ahn1OQU21S5DowCbF7IIwWhhVrq7jl1hp42mpFS6a8r2ZF+DpIFfBXgY50z9nkUHbJS6CGIA5PP8Exe6+AI=
