language: java
sudo: false

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: 2NZIWUbWXqzsd6OnSbf58oiS7uxuL1AAAwJzSXmEEOIlxCksQPKUh3mZuo3CE4hY9zpnDiwWr5ax5MfWmxayIOn1CoAzZmbAAi9gzbAOPfLqe+OXUuIvunHvi1SaBx07MqpVrOFLr1phc5YA7REd1B2bmOOAhZe/LUWQsQvxFMfKXPgXK3JFjJLecjQ1DpyfNO/czW/P2x2H5OQuwsdekI8xhD0+0axAH8kKrfdsLHaLMZpdFttKANY/xZw3EIA52x/WHOEOq/s2ctiw6MUZiHINFckAYjHXWHph63nDjL373Qj0toTsJBnPKxF8xd96Ging2n0C3s3XHQazSUAySTQ/Q7ZnBaJR+K7gAxldXlYDwTDAKnALQVUlmgcrSFEaARr1onj99OmwpvAzcgwpXcige6YPVV90SJAKvnwoieQcY8POY57BlP0V8CZ5MkwMTBFQXigr5O6dNwShpRnInum6xFlNMqr0ECgAGq25d/sY5s/hKoDtS2oh95hbdEBng/6nK2kRO++uOgj/o+qu+ZZKvdAKC3uSeb984VVShEp+u5aVKjEMxRDv346h+Ur+MstFqG8jSCdFF8CkavOpsQssOuBvorR8duGaUo9gzoP/6WlHG1J/yDf7WUyKX9L4zv5mEteg1pU1k4qJ7KH8o+CirSDPXes1VxSyz377OJg=
    - secure: vE5bNXj+k41hFgGTTVq0YGQ1aUiv8CtQh+IbkEFyL/uD9ZQIqWWlxOYn1XE8aDVURJ+1exZkT6JNlyQC2syUyEgS+Acx2Y7GjjwNgkiB+B5Ziln5gHeLtc5dFmEOLLwm23DsUh7+tZ/4vWxrXN0wENFfrrpkA6YJD2a/OSYGO0qy7aCnzRPG8XfiXexpceJLPFBrLV2LztYUm5M2fFFnZ9FPrJPtfbnlTdaS7dkLU6rJ9nWqMIPbFRTbnPrwkptzys6G3sKLuZmQf8BnAGAgzyhMUSs44F3NC5OixBPTeFv1aFCh1eaAQOEMOQhDr+WW0mp+e/YIR0cACwUnlgYHSlV4unQMW3N46ryjxNpl4LoirXPrI5oKt1jYAAApQrN1gqN6bzK7nXn5EWRvXY68CFauumA3qk/dGOD0CBHmXPKUJr/6DXXEhPYqHtoyIE7Ls1XPmTbeifYGWi2KuayJATcdRHnQIikZ0bLTk8X53arPvZOSkFzUFR54Ex5hLrRMHKbNF73EwhF/LTbsBCipI5BH+I5o5aH+IbGBcZdg5mnPF0RsE9OH1rXz768hWqIWE8ZbkHWUOwJjq2emTLgd+qk0hyykg5MwJnGontoU2CFyvsPzqFjnCsgdNovkZrvcvX+jCUIVSs2Q4cz/IXs6uly1GaPTFprUocHZul82Zsc=
